### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Parcelable encountered IOException writing serializable object (name = org.smartregister.growthmonitoring.domain.WeightWrapper)

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#139]
https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59c4e182be077a4dcc0bf7ee?time=last-seven-days

Fatal Exception: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.smartregister.growthmonitoring.domain.WeightWrapper)
       at android.os.Parcel.writeSerializable(Parcel.java:1536)
       at android.os.Parcel.writeValue(Parcel.java:1484)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:733)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:773)
       at android.app.FragmentState.writeToParcel(Fragment.java:147)
       at android.os.Parcel.writeTypedArray(Parcel.java:1316)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
       at android.os.Parcel.writeParcelable(Parcel.java:1505)
       at android.os.Parcel.writeValue(Parcel.java:1411)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:733)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:773)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4172)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4198)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by java.io.NotSerializableException: org.smartregister.domain.Photo
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
       at android.os.Parcel.writeSerializable(Parcel.java:1531)
       at android.os.Parcel.writeValue(Parcel.java:1484)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:733)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:773)
       at android.app.FragmentState.writeToParcel(Fragment.java:147)
       at android.os.Parcel.writeTypedArray(Parcel.java:1316)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
       at android.os.Parcel.writeParcelable(Parcel.java:1505)
       at android.os.Parcel.writeValue(Parcel.java:1411)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:733)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:773)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4172)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4198)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by ekigamba** [comment]
This issue is related to the following Issues on Crashlytics:

1. https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59d7f3d7be077a4dccde842f?time=last-seven-days
1. https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59edf12161b02d480d101362?time=last-seven-days

**Comment by ekigamba** [comment]
How to replicate:

1. Go to a child's vaccine card
2. Click on a vaccine button which should open the Vaccine Edit dialog
3. Click on the **device's** home button

This will make the device to crash
