### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException An error occurred while executing doInBackground() caused by org.smartregister.client.GZipEncodingHttpClient.execute

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#142]
https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59c533a9be077a4dcc108fcb?time=last-thirty-days

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=https//:zeir.smartregister/opensrp/security/authenticate
       at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:2702)
       at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1267)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:700)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
       at org.smartregister.client.GZipEncodingHttpClient.execute(GZipEncodingHttpClient.java:37)
       at org.smartregister.service.HTTPAgent.urlCanBeAccessWithGivenCredentials(HTTPAgent.java:126)
       at org.smartregister.service.UserService.isValidRemoteLogin(UserService.java:284)
       at org.smartregister.path.activity.LoginActivity$RemoteLoginTask.doInBackground(LoginActivity.java:518)
       at org.smartregister.path.activity.LoginActivity$RemoteLoginTask.doInBackground(LoginActivity.java:499)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by keymane** [comment]
How to reproduce: Before logging, go to the settings page and add an invalid url e.g. http//:abc.com, http://:abc.dz
