### ISSUE TITLE
PathJsonFormActivity.java line 441 org.smartregister.path.activity.PathJsonFormActivity.stockVialsenteredinReceivedForm

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#151]
Crashlytics issue https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59d14aa0be077a4dcc96abd1?time=last-thirty-days

Fatal Exception: java.lang.NumberFormatException: Invalid int: "1."
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at java.lang.Integer.parseInt(Integer.java:334)
       at org.smartregister.path.activity.PathJsonFormActivity.stockVialsenteredinReceivedForm(PathJsonFormActivity.java:441)
       at org.smartregister.path.activity.PathJsonFormActivity.refreshCalculateLogic(PathJsonFormActivity.java:60)
       at org.smartregister.path.activity.PathJsonFormActivity.writeValue(PathJsonFormActivity.java:50)
       at com.vijay.jsonwizard.customviews.GenericTextWatcher.afterTextChanged(GenericTextWatcher.java:70)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:7765)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9818)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:972)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:516)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:184)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by keymane** [comment]
How to reproduce: In the stock received form, enter a decimal value in the vials received field

**Comment by cagulas** [comment]
Decimals should not be allowed. Can we add a constraint to prevent this?
