### ISSUE TITLE
FragmentManager.java line 1237 android.app.FragmentManagerImpl.addFragment

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#153]
Crashlytics issue https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59e866ff61b02d480dd39f7b?time=last-thirty-days

Fatal Exception: java.lang.IllegalStateException: Fragment already added: VaccinationDialogFragment{7d0772f #0 ChildImmunoActivity_DIALOG_TAG}
       at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1237)
       at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1630)
       at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1661)
       at android.app.FragmentManagerImpl$4.run(FragmentManager.java:610)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7231)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ekigamba** [comment]
Other issues caused by the same bug:

https://fabric.io/ona-systems/android/apps/org.smartregister.path/issues/59e99b3d61b02d480de18434?time=last-thirty-days

**Comment by keymane** [comment]
How to reproduce: In the vaccine card, click on two different vaccine buttons at the same time.

**Comment by cagulas** [comment]
Lgtm. No crashing.
